# SwiftLint Configuration for TicketShape

# Paths to include/exclude during linting
included:
  - Sources
  - Tests
excluded:
  - .build
  - Package.swift
  - .swiftpm

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length # We'll configure this instead

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - closure_spacing
  - collection_alignment
  - convenience_type
  - discouraged_object_literal
  - explicit_acl
  - explicit_top_level_acl
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_imports
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

nesting:
  type_level:
    warning: 2
    error: 3

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  .*?
                    \/\/
                    \/\/  Created by .* on \d{2}\/\d{2}\/\d{2}\.
                    \/\/

# Custom rules
custom_rules:
  double_space:
    name: "Double space"
    regex: "([a-z,A-Z] \s+)"
    message: "Double space between words"
    match_kinds: comment
    severity: warning

  comments_space:
    name: "Space After Comment"
    regex: "(^ *//\w+)"
    message: "There should be a space after //"
    severity: warning

  empty_first_line:
    name: "Empty First Line"
    regex: "(^[ a-zA-Z ]*(?:protocol|extension|class|struct) (?!(?:var|let))[ a-zA-Z:]*\{\n *\S+)"
    message: "There should be an empty line after a declaration"
    severity: warning

# Reporter type
reporter: "xcode"
